CREATE TABLE IF NOT EXISTS b_user_inf (
 user_id VARCHAR(10) NOT NULL PRIMARY KEY,
 user_name VARCHAR(20) NOT NULL,
 mail_addr VARCHAR(80) NOT NULL,
 corp_id VARCHAR(3) DEFAULT '000',
 department VARCHAR(3) DEFAULT '000',
 grade INT,
 gender VARCHAR(1) NOT NULL,
 birth TIMESTAMP NOT NULL,
 career_yrs INT NOT NULL
);

CREATE TABLE IF NOT EXISTS b_mental_scale (
 mscale_num VARCHAR(10) NOT NULL PRIMARY KEY,
 s_date TIMESTAMP NOT NULL,
 avg_score DOUBLE NOT NULL,
 max_score INT NOT NULL,
 min_score INT NOT NULL
);

CREATE TABLE IF NOT EXISTS b_mental_scale_detail (
 mscale_num VARCHAR(10) NOT NULL PRIMARY KEY,
 user_id VARCHAR(10) NOT NULL,
 s_date TIMESTAMP NOT NULL,
 m001 INT,
 m002 INT,
 m003 INT,
 m004 INT,
 m005 INT,
 m006 INT,
 m007 INT,
 m008 INT,
 m009 INT,
 m010 INT,
 m011 INT,
 m012 INT,
 m013 INT,
 m014 INT,
 m015 INT,
 m016 INT,
 m017 INT,
 m018 INT,
 m019 INT,
 m020 INT,
 other TEXT
);

CREATE TABLE IF NOT EXISTS m_mental (
 ques_key VARCHAR(4) NOT NULL PRIMARY KEY,
 ques_detail TEXT
);

CREATE SEQUENCE mscale_num_seq_2025 START WITH 1;
CREATE SEQUENCE mscale_num_seq_2026 START WITH 1;