#app info
spring.application.name=mentalscale_api

#log info
logging.config=classpath:logback-spring.xml

#database info
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.encoding=UTF-8
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql

#h2\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9\u306e\u30b3\u30f3\u30bd\u30fc\u30eb\u753b\u9762\u5229\u7528\u306e\u5834\u5408\uff08http://localhost:8080/h2-console\uff09
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true